name: proxybroker2-docs
dependencies:
- python>=3.10
- pip
- setuptools
- wheel
- pip:
  - sphinx>=8.0
  - myst-parser>=4.0
  - alabaster>=1.0.0
  - aiohttp>=3.12.0
  - aiodns>=3.4.0
  - maxminddb>=2.7.0
  - attrs>=25.3.0
  - cachetools>=5.5.2
  - click>=8.2.1
